### ISSUE TITLE
feat: Study Group Landing Page

### ISSUE THREAD

**Issue by dricazenck** [WomenCodingCommunity/WomenCodingCommunity.github.io#123]
### Description

Create content for study group and the landing page for it, to make the nav bar consistent. 

The content could be asked to the team or propose suggestion to be reviewed. 

Related to issue https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/115

Related to issue https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/121

**Comment by lilyndk** [comment]
Hi @goelsonali, all the component refactoring changes have been merged today related to the branding re-design, thus please ensure to pull down latest changes from main branch, thanks.

**Comment by goelsonali** [comment]
@lilyndk @dricazenck - Does it look ok to proceed or would you recommend some other changes to the content ?

<img width="1032" alt="image" src="https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/112942761/c4bb3c3a-8df3-4674-9f5c-3c95a4cd9db8">

**Comment by lilyndk** [comment]
Hi @goelsonali Yes, looks good. Please create a PR for review.
Once that's merged, I can tweak the styles to make it consistent with the other related card styles / landing page work I have in progress...since it also seems like we've accidentally been assigned to the same 'active study group' task (https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/issues/121) :) 

Thank you

**Comment by goelsonali** [comment]
@lilyndk - I have created the PR now - https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/pull/216, if you can check

**Comment by lilyndk** [comment]
@goelsonali Great, I've just added my PR comments.

**Comment by goelsonali** [comment]
Study group landing page updated with the active study group.
