### ISSUE TITLE
blog: Working with ChatGPT is all about asking the right questions

### ISSUE THREAD

**Issue by jbabahin** [WomenCodingCommunity/WomenCodingCommunity.github.io#237]
### Blog Metadata

Please provide the following information:

* Title: Working with ChatGPT is all about asking the right questions
* Author: Silke Nodwell 
* Position / Company: Data Scientist at TAC Index 
* Date: 20th May 2024 
* Short description: Working with ChatGPT is all about asking the right questions
* Google doc Link with the content: https://docs.google.com/document/d/1dGSadWrQWEOyYKPNfKNwf6UJozYEdGrx7mCmqnU9NCI/edit
* Category:

### Banner image - SEE IN THE GOOGLE DOC 

Please include the banner image link for your post as a suggestion.
Keep in mind the image should be free or your own image creation.
In case you don't have any, the team can suggest.

Is there other images you want to include the content? Please include their links here also.

**Comment by lilyndk** [comment]
Hi @jbabahin , thanks for submitting the blog post. Please attach the image here (so we have it in high quality format) and stock photo source name/link if it's not an image of your own creation. Thanks

**Comment by lilyndk** [comment]
@nora-weisser @dricazenck we should maybe update the blog post GitHub submission template to make it more clear that we need: 
1) The image attached here or an image download source link (so we have it in high quality format)
2) Image stock photo source name/link, since many free sources still require some credit somewhere on the site. We could add the blog article photo credit as an 'image caption' text.
- Perhaps recommend unsplash.com which we've been using a lot so far as a free stock image site resource.
- I also need to create a task to list credits of the stock photos used on our other pages, I guess that could just be under 'About' page for now?

**Comment by jbabahin** [comment]
For Silke's blog the image is attached. It was created via Dall-e. Is this OK? 
![ChatGPT_blog_illustration](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/170346454/dfa46125-02cf-4f53-8476-d3edb186c894)

**Comment by jbabahin** [comment]
For Arzu's blog post, it was created in Canva and is attached. 
![Picture 1](https://github.com/WomenCodingCommunity/WomenCodingCommunity.github.io/assets/170346454/09fc14ba-5a97-4e87-9e55-85cb2621fd80)

**Comment by jbabahin** [comment]
Let me know if anything else is required for these blog posts to be published :)
