### ISSUE TITLE
feat: Improve home page for visitors/new users

### ISSUE THREAD

**Issue by khairahscorner** [WomenCodingCommunity/WomenCodingCommunity.github.io#359]
### Is your feature request related to a problem? Please describe.
A discussion happened on how our current website home page does not properly present the minimum complete information for visitors or anyone new to the community to understand what we do and how they can engage or contribute to the community.

### Describe the solution you'd like
There were some suggestions made, please feel free to add more in the comments:
- Improve website home page
  - First section of the page can be improved e.g **'Do you want to volunteer with us?'** can be changed to: **'Who We Are & What We Do'** or better
  - Move opportunities and programmes sections up (same with mentors/mentees section, this can have a heading 'Mentorship Programme Spotlight') 
  - Improve 'Events' section: add brief introductory details, make more concise, etc
  - Additional Section for 'Volunteering'

**Comment by dricazenck** [comment]
@khairahscorner could you bring to @lilyndk as well, because she has designed the layout for our new website, I understand that are many things to improve, but I think we should consider the less changes to the current website to actually have the time to focus in the new website implementation. But I think this is a very important topic and we need to consider these points into the new version. 
I think you are going to join our next meeting, please bring all ideas and we can discuss about that.

**Comment by goelsonali** [comment]
As discussed, @dricazenck  - We will move the programs section in place of the volunteer section and add a link to "Join us on Slack" on the homepage banner.

**Comment by khairahscorner** [comment]
improved by #365
